name: Publish
on:
  push:
    branches:
      - main
      - develop
      - release/*
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      # If develop add -beta to version
      - name: Set version for develop branch
        if: github.ref == 'refs/heads/develop'
        working-directory: library
        run: |
          jq '.version += "-beta.${{ github.run_number }}"' deno.json > tmp.$$.json && mv tmp.$$.json deno.json

      - name: Publish package
        working-directory: library
        run: |
          if [ "${{ github.ref }}" = "refs/heads/develop" ]; then
            npx jsr publish --allow-dirty
          else
            npx jsr publish
          fi